
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - database
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    networks:
      - app_network

  database:
    image: postgres:latest
  #envfile: ./tddb.env
    container_name: slim_db
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    volumes:
      - ./app/sql:/var/sql
    networks:
      - app_network

  directus:
    image: directus/directus
    container_name: directus_graphql
    environment:
      DIRECTUS_DATABASE_CLIENT: postgres
      DIRECTUS_DATABASE_HOST: database
      DIRECTUS_DATABASE_PORT: 5432
      DIRECTUS_DATABASE_NAME: directus
      DIRECTUS_DATABASE_USER: directus
      DIRECTUS_DATABASE_PASSWORD: directus
    ports:
      - "8055:8055"
    depends_on:
      - database
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "20000:8080"
    depends_on:
      - database
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
